module Opts
  ( optDescrs
  , parseOpts
  , applyOpts
  ) where

import Data.Monoid
import Data.Semigroup hiding (Option)
import System.Console.GetOpt
import Text.Read

import Settings

-- Endomorphism in the Kleisli category generated by `Either String`
newtype Opt = Opt { runOpt :: Settings -> Either String Settings }
instance Semigroup Opt where
  Opt a <> Opt b = Opt (\x -> b x >>= a)
instance Monoid Opt where
  mempty = Opt pure

optDescrs :: [OptDescr Opt]
optDescrs =
    [ Option "p" ["port"] portArg "What port to listen on"
    , Option "h" ["host"] hostArg "What host to listen on"
    , Option ""  ["path"] pathArg "TODO: add description of --path"
    , Option "r" ["root"] rootArg "Root folder"
    , Option ""  ["help"] helpArg "Show command usage"
    , Option ""  ["404"]  _404Arg "404 page"
    ]
  where
    portArg, hostArg, pathArg, rootArg, _404Arg :: ArgDescr Opt
    portArg = ReqArg portHandler                                              ""
    hostArg = ReqArg (\host -> Opt (\set -> pure (set { hhostHost = host }))) ""
    rootArg = ReqArg (\root -> Opt (\set -> pure (set { hhostRoot = root }))) ""
    _404Arg = ReqArg (\_404 -> Opt (\set -> pure (set { hhost404  = _404 }))) ""
    pathArg = ReqArg (error "--path: NYI")                                    ""
    helpArg = NoArg (Opt (\set -> pure (set { hhostHelp = True })))

    portHandler :: String -> Opt
    portHandler str = Opt $ \set -> case readMaybe str of
      Nothing            -> Left $ "Port doesn't parse: " ++ show str
      Just n | n < 0     -> Left $ "Port too low: " ++ show n
             | n > 25565 -> Left $ "Port too high: " ++ show n
             | otherwise -> pure (set { hhostPort = n })

parseOpts :: [String] -> ([Opt], [String], [String])
parseOpts args = getOpt Permute optDescrs args

applyOpts :: [String] -> Settings -> Either [String] (Settings, [String])
applyOpts args set =
  let (perm, nonopts, errors) = parseOpts args
  in case errors of
    [] -> case runOpt (mconcat perm) set of
      Left err  -> Left [err]
      Right res -> Right (res, nonopts)
    errs -> Left errs
